AppBundle\Entity\Task:
    properties:
        title:
            - NotBlank:
                message: "Vous devez saisir un titre."
            - Length:
                min: 3
                max: 50
                minMessage: "Le titre doit faire au minimum 3 caractères."
                maxMessage: "Le titre doit faire au maximum 50 caractères."
        created:
            - DateTime: ~
        content:
            - NotBlank:
                message: "Vous devez saisir du contenu."
        status:
            - Type: bool
        user:
            - Valid: ~