AppBundle\Entity\Trick:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: "Ce nom est déjà utilisé"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: "Ce mail est déjà utilisé"
    properties:
        username:
            - NotBlank:
                message: "Vous devez saisir un nom d'utilisateur."
            - Length:
                min: 3
                max: 25
                minMessage: "Le nom d'utilisateur doit faire au minimum 3 caractères."
                maxMessage: "Le nom d'utilisateur doit faire au maximum 25 caractères."
        email:
            - Length:
                max: 60
                maxMessage: "L'adresse mail doit faire au maximum 60 caractères."
            - NotBlank:
                message: "Vous devez saisir une adresse email."
            - Email:
                message: "Le format de l'adresse n'est pas correct."
        tasks:
            - Valid:
                traverse: true