# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_create_handler:
        class: AppBundle\Handler\UserCreateHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder"]

    app.user_edit_handler:
        class: AppBundle\Handler\UserEditHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder"]

    app.task_create_handler:
        class: AppBundle\Handler\TaskCreateHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    app.task_edit_handler:
        class: AppBundle\Handler\TaskEditHandler
        arguments: ["@doctrine.orm.entity_manager"]